### ISSUE TITLE
Download profile failed with error.HTTP Response Status Code(400)

### ISSUE THREAD

**Issue by stone2monkey** [MessCode994/ClashConfig#2]
大佬，我选择的配置是 Windows/rule.ini 
对应的raw是：https://raw.githubusercontent.com/MessCode994/ClashConfig/master/rule/Windows/rule.ini

然后，我在subconverter里进行转换，客户端选择Clash
生成的订阅链接是：https://api.wcc.best/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2FMessCode994%2FClashConfig%2Fmaster%2Frule%2FWindows%2Frule.ini

我在浏览器里打开这个链接，则显示是：The following link doesn't contain any valid node info: https://raw.githubusercontent.com/MessCode994/ClashConfig/master/rule/Windows/rule.ini

我在Clash客户端里进行下载，则显示：Download profile failed with error.HTTP Response Status Code(400)

请问是我操作方法有问题吗？？

在这里再次感谢大佬，没想到大佬这么热情，竟然亲自回复我了，鸡冻。。

**Comment by MessCode994** [comment]
@stone2monkey 选择远程链接里填这一部分，URL后面是跟的你机场的订阅链接或者是自建的链接.

**Comment by MessCode994** [comment]
@stone2monkey

**Comment by MessCode994** [comment]
@stone2monkey https://t.me/me_support_tech_fw
这是我tg，有啥不会的来tg私我吧
