### ISSUE TITLE
谢谢大佬

### ISSUE THREAD

**Issue by stone2monkey** [MessCode994/ClashConfig#3]
大佬，我懂了，这个就是一个配置文件，自己的订阅链接安装这个配置文件生成新的订阅链接，然后导入clash就行了。

我导入clash，但是速度和我原来的订阅链接速度一样，没啥区别

现在，我有点不太明白这个配置文件主要起什么作用呢？？

我没玩过电报，以后关注你。大佬有油管号吗，我去订阅你

**Comment by MessCode994** [comment]
@stone2monkey 这个主要起分流的作用，如果对策略租没什么要求的话，不需要关心这东西，我本人不玩YT，电报也只是我的私聊，没创群组.
